apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: pingwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: IMAGE_TAG_WORKER
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: DATABASE_URL
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: SMTP_PASS
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: pingwatch-secrets
                  key: SMTP_FROM
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
